# -*- coding: utf-8 -*-
"""full-text-test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MbmfBeyqPa5YEWvdM0fuw9Juw1Yib7ZC
"""

import pandas as pd

file_path = "/content/drive/MyDrive/Jun 2023/full_text_file5.txt"

# Open the file in read mode
with open(file_path, 'r') as file:
    line_count = 0
    for line in file:
        line_count += 1

print("Number of lines:", line_count)

column_titles = ["core_id", "full_text"]

file_path = "/content/drive/MyDrive/Jun 2023/full_text_file5.txt"

full_text = pd.read_csv(file_path, sep="\t",header=None, names=column_titles)

full_text

# Load the second file
df1 = pd.read_csv("/content/drive/MyDrive/Jun 2023/sdp_act/test.txt",sep="\t")

df1

# Merge the two dataframes on the 'id' column
merged = pd.merge(df1, full_text, on='core_id',how='inner')

merged

merged['full_text'].count()

merged['full_text'].notnull().sum()

merged['full_text'].str.len().mean()

# Write the merged dataframe to a new file
merged.to_csv('/content/drive/MyDrive/Jun 2023/merged_test.txt',sep='\t', index=False)

df2 = pd.read_csv("/content/drive/MyDrive/Jun 2023/merged_test.txt",sep="\t")

df2









